apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: do-nvtop
spec:
  selector:
    matchLabels:
      name: do-nvtop
  template:
    metadata:
      labels:
        name: do-nvtop
    spec:
      containers:
        - name: do-nvtop
          image: iankoulski/do-nvtop
          command: ["/bin/sh"]
          args: ["-c", "while true; do date; sleep 10; done"]
